/*
 * Copyright (C) the libgit2 contributors. All rights reserved.
 *
 * This file is part of libgit2, distributed under the GNU GPL v2 with
 * a Linking Exception. For full terms see the included COPYING file.
 */

#ifndef INCLUDE_git_git_h__
#define INCLUDE_git_git_h__

#include "libgit2/annotated_commit.h"
#include "libgit2/apply.h"
#include "libgit2/attr.h"
#include "libgit2/blob.h"
#include "libgit2/blame.h"
#include "libgit2/branch.h"
#include "libgit2/buffer.h"
#include "libgit2/cert.h"
#include "libgit2/checkout.h"
#include "libgit2/cherrypick.h"
#include "libgit2/clone.h"
#include "libgit2/commit.h"
#include "libgit2/common.h"
#include "libgit2/config.h"
#include "libgit2/credential.h"
#include "libgit2/deprecated.h"
#include "libgit2/describe.h"
#include "libgit2/diff.h"
#include "libgit2/email.h"
#include "libgit2/errors.h"
#include "libgit2/experimental.h"
#include "libgit2/filter.h"
#include "libgit2/global.h"
#include "libgit2/graph.h"
#include "libgit2/ignore.h"
#include "libgit2/index.h"
#include "libgit2/indexer.h"
#include "libgit2/mailmap.h"
#include "libgit2/merge.h"
#include "libgit2/message.h"
#include "libgit2/net.h"
#include "libgit2/notes.h"
#include "libgit2/object.h"
#include "libgit2/odb.h"
#include "libgit2/odb_backend.h"
#include "libgit2/oid.h"
#include "libgit2/pack.h"
#include "libgit2/patch.h"
#include "libgit2/pathspec.h"
#include "libgit2/proxy.h"
#include "libgit2/rebase.h"
#include "libgit2/refdb.h"
#include "libgit2/reflog.h"
#include "libgit2/refs.h"
#include "libgit2/refspec.h"
#include "libgit2/remote.h"
#include "libgit2/repository.h"
#include "libgit2/reset.h"
#include "libgit2/revert.h"
#include "libgit2/revparse.h"
#include "libgit2/revwalk.h"
#include "libgit2/signature.h"
#include "libgit2/stash.h"
#include "libgit2/status.h"
#include "libgit2/submodule.h"
#include "libgit2/tag.h"
#include "libgit2/transport.h"
#include "libgit2/transaction.h"
#include "libgit2/tree.h"
#include "libgit2/types.h"
#include "libgit2/version.h"
#include "libgit2/worktree.h"

#endif
